<script setup>
import { onBeforeUnmount, ref, watch } from "vue"; import { useRoute, useRouter } from "vue-router"; import { useI18n } from "vue-i18n";
import AppHeader from "../components/AppHeader.vue"; import BottomNav from "../components/BottomNav.vue"; import StoryCard from "../components/StoryCard.vue"; import { fetchNovelList } from "../lib/api.js"; import { normalizedQuery } from "../lib/content.js"; import { createRequestGate } from "../lib/request.js";
const route=useRoute(),router=useRouter(),query=ref(String(route.query.q||"")),items=ref([]),loading=ref(false),searched=ref(false),error=ref(""); let timer;
const { locale, t } = useI18n({ useScope:"global" });
const requestGate=createRequestGate();
async function search(){const version=requestGate.next(),q=normalizedQuery(query.value),selectedLocale=locale.value;if(!q){items.value=[];searched.value=false;loading.value=false;error.value="";const next={...route.query};delete next.q;router.replace({query:next});return;}loading.value=true;error.value="";router.replace({query:{...route.query,q}});try{const result=await fetchNovelList(route.params.code,{q,page:1,pageSize:30,locale:selectedLocale});if(!requestGate.isCurrent(version))return;items.value=result.items;searched.value=true;}catch(e){if(requestGate.isCurrent(version))error.value=e.message;}finally{if(requestGate.isCurrent(version))loading.value=false;}}
watch(query,()=>{clearTimeout(timer);timer=setTimeout(search,350);});watch(locale,()=>{if(normalizedQuery(query.value))search();});if(normalizedQuery(query.value)) search(); onBeforeUnmount(()=>{requestGate.cancel();clearTimeout(timer);});
</script>
<template><div class="page with-nav"><header class="search-header"><AppHeader back :show-search="false" /><label class="search-box"><i class="fa-solid fa-magnifying-glass" /><input v-model="query" autofocus type="search" :placeholder="t('searchPlaceholder')" :aria-label="t('searchStories')" /><button v-if="query" :aria-label="t('clearSearch')" @click="query=''">×</button></label></header><section class="search-content"><div v-if="loading" class="state-block compact-state"><i class="fa-solid fa-spinner fa-spin" /><p>{{ t('searching') }}</p></div><div v-else-if="error" class="state-block compact-state"><p class="error-text">{{ error }}</p><button class="secondary-button" @click="search">{{ t('retry') }}</button></div><div v-else-if="items.length" class="story-grid"><StoryCard v-for="story in items" :key="story.id" :story="story" /></div><div v-else-if="searched" class="state-block"><i class="fa-regular fa-face-meh" /><p>{{ t('noMatches',{query:normalizedQuery(query)}) }}</p></div><div v-else class="search-hint"><i class="fa-solid fa-feather-pointed" /><p>{{ t('searchHint') }}</p></div></section><BottomNav /></div></template>
