<script setup>
import { nextTick, onBeforeUnmount, onMounted, ref, watch } from "vue"; import { useRoute, useRouter } from "vue-router";
import AppHeader from "../components/AppHeader.vue"; import ChapterDrawer from "../components/ChapterDrawer.vue"; import StoryCard from "../components/StoryCard.vue"; import { fetchNovelChapter, fetchNovelStory } from "../lib/api.js"; import { readProgress, saveProgress } from "../lib/progress.js"; import { progressChapter } from "../lib/reader.js";
const route=useRoute(),router=useRouter(),story=ref(),chapters=ref([]),related=ref([]),chapter=ref(),previous=ref(),next=ref(),loading=ref(true),chapterLoading=ref(false),error=ref(""),drawer=ref(false); let scrollTimer;
async function loadChapter(number,{restore=0,scroll=true}={}){chapterLoading.value=true;try{const data=await fetchNovelChapter(route.params.code,route.params.slug,number);chapter.value=data.chapter;previous.value=data.previous;next.value=data.next;await router.replace({query:{chapter:data.chapter.chapter_number}});await nextTick();if(scroll)document.getElementById("reading")?.scrollIntoView({behavior:"smooth"});else if(restore)window.scrollTo({top:restore});saveProgress(route.params.slug,data.chapter.chapter_number,restore);}catch(e){error.value=e.message;}finally{chapterLoading.value=false;}}
async function start(){document.getElementById("reading")?.scrollIntoView({behavior:"smooth"});}
async function select(number){drawer.value=false;await loadChapter(number);}
function saveScroll(){clearTimeout(scrollTimer);scrollTimer=setTimeout(()=>{if(chapter.value)saveProgress(route.params.slug,chapter.value.chapter_number,window.scrollY);},250);}
onMounted(async()=>{window.addEventListener("scroll",saveScroll,{passive:true});try{const data=await fetchNovelStory(route.params.code,route.params.slug);story.value=data.story;chapters.value=data.chapters;related.value=data.related;const numbers=data.chapters.map(item=>item.chapter_number),saved=readProgress(route.params.slug,numbers),requested=Number(route.query.chapter),number=progressChapter(data.chapters,requested||saved?.chapterNumber);if(number)await loadChapter(number,{restore:requested?0:saved?.scrollY||0,scroll:false});}catch(e){error.value=e.message;}finally{loading.value=false;}});
onBeforeUnmount(()=>{window.removeEventListener("scroll",saveScroll);clearTimeout(scrollTimer);}); watch(()=>route.params.slug,()=>window.location.reload());
</script>
<template><div class="reader-page"><div v-if="loading" class="state-page"><i class="fa-solid fa-spinner fa-spin" /><p>Opening story…</p></div><div v-else-if="error&&!story" class="state-page"><i class="fa-solid fa-triangle-exclamation" /><p>{{ error }}</p></div><template v-else><section class="story-hero" :style="story.cover_path?{'--cover':`url(${story.cover_path})`}:{}"><div class="hero-overlay"><!-- 搜索与章节目录共用头部弹性布局，保证移动端按钮互不遮挡。 --><AppHeader back><button v-if="chapters.length" class="menu-button" aria-label="Open contents" @click="drawer=true"><i class="fa-solid fa-bars" /></button></AppHeader><div class="hero-content"><div class="hero-cover"><img v-if="story.cover_path" :src="story.cover_path" :alt="`${story.title} cover`" /><i v-else class="fa-solid fa-book-open" /></div><div><h1>{{ story.title }}</h1><p>{{ story.author || 'Anonymous' }}</p><small>{{ story.chapter_count }} chapters</small></div></div></div></section><article class="story-body"><p class="story-excerpt">{{ story.excerpt }}</p><button v-if="chapters.length" class="primary-button" @click="start">Start Reading</button><div v-else class="state-block compact-state"><i class="fa-solid fa-book-open" /><p>This story has no readable chapters yet. Please check back later.</p></div><section v-if="chapters.length" id="reading" class="chapter-content" aria-live="polite"><div class="chapter-heading"><div><span>Chapter {{ chapter?.chapter_number }}</span><h2>{{ chapter?.title || story.title }}</h2></div><button class="contents-button" @click="drawer=true"><i class="fa-solid fa-list" /> Contents</button></div><div v-if="chapterLoading" class="state-block compact-state"><i class="fa-solid fa-spinner fa-spin" /></div><div v-else-if="chapter" class="prose" v-html="chapter.body_html" /><p v-if="error" class="error-text">{{ error }}</p><div v-if="chapter" class="chapter-actions"><button v-if="previous" class="secondary-button" @click="loadChapter(previous.chapter_number)"><i class="fa-solid fa-chevron-left" /> Previous</button><button v-if="next" class="primary-button" @click="loadChapter(next.chapter_number)">Continue Reading <i class="fa-solid fa-chevron-right" /></button><span v-else class="finished"><i class="fa-solid fa-circle-check" /> You reached the end</span></div></section><section v-if="related.length" class="related"><h2>You may also like</h2><div class="story-grid"><StoryCard v-for="item in related" :key="item.id" :story="item" /></div></section></article><ChapterDrawer :open="drawer" :chapters="chapters" :current="chapter?.chapter_number" @close="drawer=false" @select="select" /></template></div></template>
