import { computed } from "vue";
import { createI18n } from "vue-i18n";

const en = {
  appTitle:"Free Stories — Read Online", home:"Home", stories:"Stories", search:"Search", goBack:"Go back", storyHome:"Story home", searchStories:"Search stories", chooseLanguage:"Choose language",
  openingShelf:"Opening the story shelf…", retry:"Try again", featuredStories:"Featured stories", startReading:"Start Reading", previousFeatured:"Previous featured story", nextFeatured:"Next featured story", chooseFeatured:"Choose featured story", showFeatured:"Show featured story {number}", ranking:"Ranking", popularStories:"Popular Stories", more:"More", noStories:"No stories have been published yet.",
  searchPlaceholder:"Search stories", clearSearch:"Clear search", searching:"Searching…", noMatches:"No stories match “{query}”.", searchHint:"Find your next story by title, author, or category.", browseShelf:"Browse the shelf", allStories:"All Stories", loading:"Loading…", loadMore:"Load more",
  openingStory:"Opening story…", openContents:"Open contents", anonymous:"Anonymous", chapterCount:"{count} chapters", noReadableChapters:"This story has no readable chapters yet. Please check back later.", chapter:"Chapter {number}", contents:"Contents", previous:"Previous", continueReading:"Continue Reading", reachedEnd:"You reached the end", mayAlsoLike:"You may also like", closeContents:"Close contents", cover:"{title} cover", restingTitle:"Stories are resting", restingMessage:"This story archive is unavailable.",
  unavailable:"This story archive could not be loaded.", incomplete:"The archive returned an incomplete response.", notFound:"This story could not be found."
};

const withEnglishKeys = (values) => ({ ...en, ...values });
export const dictionaries = {
  en,
  id:withEnglishKeys({ appTitle:"Cerita Gratis — Baca Online",home:"Beranda",stories:"Cerita",search:"Cari",goBack:"Kembali",storyHome:"Beranda cerita",searchStories:"Cari cerita",chooseLanguage:"Pilih bahasa",openingShelf:"Membuka rak cerita…",retry:"Coba lagi",featuredStories:"Cerita pilihan",startReading:"Mulai Membaca",previousFeatured:"Cerita pilihan sebelumnya",nextFeatured:"Cerita pilihan berikutnya",chooseFeatured:"Pilih cerita pilihan",showFeatured:"Tampilkan cerita pilihan {number}",ranking:"Peringkat",popularStories:"Cerita Populer",more:"Lainnya",noStories:"Belum ada cerita yang diterbitkan.",searchPlaceholder:"Cari cerita",clearSearch:"Hapus pencarian",searching:"Mencari…",noMatches:"Tidak ada cerita yang cocok dengan “{query}”.",searchHint:"Temukan cerita berdasarkan judul, penulis, atau kategori.",browseShelf:"Jelajahi rak",allStories:"Semua Cerita",loading:"Memuat…",loadMore:"Muat lagi",openingStory:"Membuka cerita…",openContents:"Buka daftar isi",anonymous:"Anonim",chapterCount:"{count} bab",noReadableChapters:"Cerita ini belum memiliki bab yang dapat dibaca.",chapter:"Bab {number}",contents:"Daftar Isi",previous:"Sebelumnya",continueReading:"Lanjut Membaca",reachedEnd:"Anda telah mencapai akhir",mayAlsoLike:"Anda mungkin juga suka",closeContents:"Tutup daftar isi",cover:"Sampul {title}",restingTitle:"Cerita sedang beristirahat",restingMessage:"Arsip cerita ini tidak tersedia.",unavailable:"Arsip cerita tidak dapat dimuat.",incomplete:"Data arsip tidak lengkap.",notFound:"Cerita ini tidak ditemukan."}),
  ja:withEnglishKeys({ appTitle:"無料小説 — オンラインで読む",home:"ホーム",stories:"小説",search:"検索",goBack:"戻る",storyHome:"小説ホーム",searchStories:"小説を検索",chooseLanguage:"言語を選択",openingShelf:"本棚を開いています…",retry:"再試行",featuredStories:"おすすめ小説",startReading:"読み始める",previousFeatured:"前のおすすめ",nextFeatured:"次のおすすめ",chooseFeatured:"おすすめを選択",showFeatured:"おすすめ小説 {number} を表示",ranking:"ランキング",popularStories:"人気小説",more:"もっと見る",noStories:"公開中の小説はありません。",searchPlaceholder:"小説を検索",clearSearch:"検索をクリア",searching:"検索中…",noMatches:"「{query}」に一致する小説はありません。",searchHint:"タイトル、作者、カテゴリから小説を探せます。",browseShelf:"本棚を見る",allStories:"すべての小説",loading:"読み込み中…",loadMore:"さらに読み込む",openingStory:"小説を開いています…",openContents:"目次を開く",anonymous:"匿名",chapterCount:"{count}章",noReadableChapters:"この小説にはまだ読める章がありません。",chapter:"第{number}章",contents:"目次",previous:"前へ",continueReading:"続きを読む",reachedEnd:"最後まで読みました",mayAlsoLike:"こちらもおすすめ",closeContents:"目次を閉じる",cover:"{title}の表紙",restingTitle:"小説は休憩中です",restingMessage:"この小説アーカイブは利用できません。",unavailable:"小説アーカイブを読み込めませんでした。",incomplete:"アーカイブのデータが不完全です。",notFound:"この小説は見つかりませんでした。"}),
  ko:withEnglishKeys({ appTitle:"무료 소설 — 온라인 읽기",home:"홈",stories:"소설",search:"검색",goBack:"뒤로",storyHome:"소설 홈",searchStories:"소설 검색",chooseLanguage:"언어 선택",openingShelf:"책장을 여는 중…",retry:"다시 시도",featuredStories:"추천 소설",startReading:"읽기 시작",previousFeatured:"이전 추천",nextFeatured:"다음 추천",chooseFeatured:"추천 소설 선택",showFeatured:"추천 소설 {number} 보기",ranking:"순위",popularStories:"인기 소설",more:"더보기",noStories:"아직 공개된 소설이 없습니다.",searchPlaceholder:"소설 검색",clearSearch:"검색 지우기",searching:"검색 중…",noMatches:"“{query}”와 일치하는 소설이 없습니다.",searchHint:"제목, 작가 또는 카테고리로 소설을 찾아보세요.",browseShelf:"책장 둘러보기",allStories:"전체 소설",loading:"불러오는 중…",loadMore:"더 불러오기",openingStory:"소설을 여는 중…",openContents:"목차 열기",anonymous:"익명",chapterCount:"{count}장",noReadableChapters:"이 소설에는 아직 읽을 수 있는 장이 없습니다.",chapter:"제{number}장",contents:"목차",previous:"이전",continueReading:"계속 읽기",reachedEnd:"마지막까지 읽었습니다",mayAlsoLike:"추천 소설",closeContents:"목차 닫기",cover:"{title} 표지",restingTitle:"소설이 잠시 쉬고 있습니다",restingMessage:"이 소설 아카이브를 이용할 수 없습니다.",unavailable:"소설 아카이브를 불러올 수 없습니다.",incomplete:"아카이브 데이터가 완전하지 않습니다.",notFound:"소설을 찾을 수 없습니다."}),
  ms:withEnglishKeys({ appTitle:"Cerita Percuma — Baca Dalam Talian",home:"Laman Utama",stories:"Cerita",search:"Cari",goBack:"Kembali",storyHome:"Laman cerita",searchStories:"Cari cerita",chooseLanguage:"Pilih bahasa",openingShelf:"Membuka rak cerita…",retry:"Cuba lagi",featuredStories:"Cerita pilihan",startReading:"Mula Membaca",previousFeatured:"Cerita pilihan sebelumnya",nextFeatured:"Cerita pilihan seterusnya",chooseFeatured:"Pilih cerita pilihan",showFeatured:"Tunjukkan cerita pilihan {number}",ranking:"Kedudukan",popularStories:"Cerita Popular",more:"Lagi",noStories:"Belum ada cerita diterbitkan.",searchPlaceholder:"Cari cerita",clearSearch:"Kosongkan carian",searching:"Mencari…",noMatches:"Tiada cerita sepadan dengan “{query}”.",searchHint:"Cari cerita mengikut tajuk, pengarang atau kategori.",browseShelf:"Terokai rak",allStories:"Semua Cerita",loading:"Memuatkan…",loadMore:"Muat lagi",openingStory:"Membuka cerita…",openContents:"Buka kandungan",anonymous:"Tanpa nama",chapterCount:"{count} bab",noReadableChapters:"Cerita ini belum mempunyai bab yang boleh dibaca.",chapter:"Bab {number}",contents:"Kandungan",previous:"Sebelumnya",continueReading:"Teruskan Membaca",reachedEnd:"Anda telah sampai ke penghujung",mayAlsoLike:"Anda mungkin juga suka",closeContents:"Tutup kandungan",cover:"Kulit {title}",restingTitle:"Cerita sedang berehat",restingMessage:"Arkib cerita ini tidak tersedia.",unavailable:"Arkib cerita tidak dapat dimuatkan.",incomplete:"Data arkib tidak lengkap.",notFound:"Cerita ini tidak ditemui."}),
  pt:withEnglishKeys({ appTitle:"Histórias Grátis — Leia Online",home:"Início",stories:"Histórias",search:"Pesquisar",goBack:"Voltar",storyHome:"Início das histórias",searchStories:"Pesquisar histórias",chooseLanguage:"Escolher idioma",openingShelf:"Abrindo a estante…",retry:"Tentar novamente",featuredStories:"Histórias em destaque",startReading:"Começar a Ler",previousFeatured:"Destaque anterior",nextFeatured:"Próximo destaque",chooseFeatured:"Escolher destaque",showFeatured:"Mostrar história em destaque {number}",ranking:"Ranking",popularStories:"Histórias Populares",more:"Mais",noStories:"Ainda não há histórias publicadas.",searchPlaceholder:"Pesquisar histórias",clearSearch:"Limpar pesquisa",searching:"Pesquisando…",noMatches:"Nenhuma história corresponde a “{query}”.",searchHint:"Encontre histórias por título, autor ou categoria.",browseShelf:"Explore a estante",allStories:"Todas as Histórias",loading:"Carregando…",loadMore:"Carregar mais",openingStory:"Abrindo história…",openContents:"Abrir sumário",anonymous:"Anônimo",chapterCount:"{count} capítulos",noReadableChapters:"Esta história ainda não possui capítulos disponíveis.",chapter:"Capítulo {number}",contents:"Sumário",previous:"Anterior",continueReading:"Continuar Lendo",reachedEnd:"Você chegou ao fim",mayAlsoLike:"Você também pode gostar",closeContents:"Fechar sumário",cover:"Capa de {title}",restingTitle:"As histórias estão descansando",restingMessage:"Este arquivo de histórias não está disponível.",unavailable:"Não foi possível carregar o arquivo.",incomplete:"O arquivo retornou dados incompletos.",notFound:"Esta história não foi encontrada."}),
  fil:withEnglishKeys({ appTitle:"Libreng Kuwento — Basahin Online",home:"Home",stories:"Mga Kuwento",search:"Maghanap",goBack:"Bumalik",storyHome:"Home ng kuwento",searchStories:"Maghanap ng kuwento",chooseLanguage:"Pumili ng wika",openingShelf:"Binubuksan ang estante…",retry:"Subukan muli",featuredStories:"Tampok na kuwento",startReading:"Magsimulang Magbasa",previousFeatured:"Nakaraang tampok",nextFeatured:"Susunod na tampok",chooseFeatured:"Pumili ng tampok",showFeatured:"Ipakita ang tampok na kuwento {number}",ranking:"Ranggo",popularStories:"Mga Sikat na Kuwento",more:"Higit pa",noStories:"Wala pang nailalathalang kuwento.",searchPlaceholder:"Maghanap ng kuwento",clearSearch:"Burahin ang paghahanap",searching:"Naghahanap…",noMatches:"Walang kuwentong tumugma sa “{query}”.",searchHint:"Maghanap ayon sa pamagat, may-akda, o kategorya.",browseShelf:"Tingnan ang estante",allStories:"Lahat ng Kuwento",loading:"Naglo-load…",loadMore:"Mag-load pa",openingStory:"Binubuksan ang kuwento…",openContents:"Buksan ang nilalaman",anonymous:"Hindi kilala",chapterCount:"{count} kabanata",noReadableChapters:"Wala pang mababasang kabanata ang kuwentong ito.",chapter:"Kabanata {number}",contents:"Nilalaman",previous:"Nakaraan",continueReading:"Magpatuloy Magbasa",reachedEnd:"Nakarating ka na sa dulo",mayAlsoLike:"Maaaring magustuhan mo rin",closeContents:"Isara ang nilalaman",cover:"Pabalat ng {title}",restingTitle:"Nagpapahinga ang mga kuwento",restingMessage:"Hindi available ang archive na ito.",unavailable:"Hindi ma-load ang archive ng kuwento.",incomplete:"Hindi kumpleto ang datos ng archive.",notFound:"Hindi nakita ang kuwentong ito."}),
  th:withEnglishKeys({ appTitle:"นิยายฟรี — อ่านออนไลน์",home:"หน้าแรก",stories:"นิยาย",search:"ค้นหา",goBack:"ย้อนกลับ",storyHome:"หน้าหลักนิยาย",searchStories:"ค้นหานิยาย",chooseLanguage:"เลือกภาษา",openingShelf:"กำลังเปิดชั้นนิยาย…",retry:"ลองอีกครั้ง",featuredStories:"นิยายแนะนำ",startReading:"เริ่มอ่าน",previousFeatured:"เรื่องแนะนำก่อนหน้า",nextFeatured:"เรื่องแนะนำถัดไป",chooseFeatured:"เลือกเรื่องแนะนำ",showFeatured:"แสดงเรื่องแนะนำ {number}",ranking:"อันดับ",popularStories:"นิยายยอดนิยม",more:"เพิ่มเติม",noStories:"ยังไม่มีนิยายที่เผยแพร่",searchPlaceholder:"ค้นหานิยาย",clearSearch:"ล้างการค้นหา",searching:"กำลังค้นหา…",noMatches:"ไม่พบนิยายที่ตรงกับ “{query}”",searchHint:"ค้นหาจากชื่อเรื่อง ผู้เขียน หรือหมวดหมู่",browseShelf:"เลือกดูชั้นนิยาย",allStories:"นิยายทั้งหมด",loading:"กำลังโหลด…",loadMore:"โหลดเพิ่มเติม",openingStory:"กำลังเปิดนิยาย…",openContents:"เปิดสารบัญ",anonymous:"ไม่ระบุชื่อ",chapterCount:"{count} ตอน",noReadableChapters:"นิยายเรื่องนี้ยังไม่มีตอนที่อ่านได้",chapter:"ตอนที่ {number}",contents:"สารบัญ",previous:"ก่อนหน้า",continueReading:"อ่านต่อ",reachedEnd:"คุณอ่านถึงตอนจบแล้ว",mayAlsoLike:"คุณอาจชอบ",closeContents:"ปิดสารบัญ",cover:"ปก {title}",restingTitle:"นิยายกำลังพัก",restingMessage:"คลังนิยายนี้ไม่พร้อมใช้งาน",unavailable:"ไม่สามารถโหลดคลังนิยายได้",incomplete:"ข้อมูลคลังนิยายไม่สมบูรณ์",notFound:"ไม่พบนิยายเรื่องนี้"}),
  vi:withEnglishKeys({ appTitle:"Truyện Miễn Phí — Đọc Trực Tuyến",home:"Trang chủ",stories:"Truyện",search:"Tìm kiếm",goBack:"Quay lại",storyHome:"Trang truyện",searchStories:"Tìm truyện",chooseLanguage:"Chọn ngôn ngữ",openingShelf:"Đang mở tủ truyện…",retry:"Thử lại",featuredStories:"Truyện nổi bật",startReading:"Bắt đầu đọc",previousFeatured:"Truyện trước",nextFeatured:"Truyện tiếp theo",chooseFeatured:"Chọn truyện nổi bật",showFeatured:"Hiển thị truyện nổi bật {number}",ranking:"Xếp hạng",popularStories:"Truyện Phổ Biến",more:"Xem thêm",noStories:"Chưa có truyện nào được xuất bản.",searchPlaceholder:"Tìm truyện",clearSearch:"Xóa tìm kiếm",searching:"Đang tìm…",noMatches:"Không có truyện phù hợp với “{query}”.",searchHint:"Tìm truyện theo tiêu đề, tác giả hoặc thể loại.",browseShelf:"Khám phá tủ truyện",allStories:"Tất Cả Truyện",loading:"Đang tải…",loadMore:"Tải thêm",openingStory:"Đang mở truyện…",openContents:"Mở mục lục",anonymous:"Ẩn danh",chapterCount:"{count} chương",noReadableChapters:"Truyện này chưa có chương nào để đọc.",chapter:"Chương {number}",contents:"Mục lục",previous:"Trước",continueReading:"Đọc tiếp",reachedEnd:"Bạn đã đọc đến cuối",mayAlsoLike:"Có thể bạn cũng thích",closeContents:"Đóng mục lục",cover:"Bìa {title}",restingTitle:"Truyện đang nghỉ",restingMessage:"Kho truyện này hiện không khả dụng.",unavailable:"Không thể tải kho truyện.",incomplete:"Dữ liệu kho truyện không đầy đủ.",notFound:"Không tìm thấy truyện này."})
};

export const localeOptions = [
  { code:"en", name:"English" }, { code:"id", name:"Bahasa Indonesia" },
  { code:"ja", name:"日本語" }, { code:"ko", name:"한국어" },
  { code:"ms", name:"Bahasa Melayu" }, { code:"pt", name:"Português" },
  { code:"fil", name:"Filipino" }, { code:"th", name:"ไทย" }, { code:"vi", name:"Tiếng Việt" },
];

// 全站共用一个 Composer，界面文案和 API 错误文案因此使用同一套字典与英文回退规则。
const plugin = createI18n({
  legacy:false,
  fallbackLocale:"en",
  locale:"en",
  messages:dictionaries,
});

export function normalizeLocale(locale, available = ["en"]) {
  return available.includes(locale) && dictionaries[locale] ? locale : "en";
}

export function translate(locale, key, parameters = {}) {
  const selected = normalizeLocale(locale, localeOptions.map(({ code }) => code));
  return plugin.global.t(key, parameters, { locale:selected });
}

export function createNovelI18n({ bootstrap, storage = globalThis.localStorage, documentRef = globalThis.document, secure = globalThis.location?.protocol === "https:" }) {
  const availableCodes = [...new Set(["en", ...(bootstrap.available_locales || [])])].filter((code) => dictionaries[code]);
  // 服务端已经按 Cookie 和 IP 完成首次识别，前端必须以 bootstrap 为准，避免旧 localStorage 覆盖国家语言。
  plugin.global.locale.value = normalizeLocale(bootstrap.locale, availableCodes);
  const locale = plugin.global.locale;
  // 菜单只展示当前小说已经完整发布的译文，避免出现无法选择的禁用项。
  const availableLocales = computed(() => localeOptions.filter(({ code }) => availableCodes.includes(code)));
  const t = (...args) => plugin.global.t(...args);
  function applyDocumentLanguage() {
    if (!documentRef) return;
    documentRef.documentElement.lang = locale.value;
    documentRef.title = t("appTitle");
  }
  async function setLocale(next) {
    // 未发布译文不能通过手写 URL 或调用控制器绕过发布状态。
    if (!availableCodes.includes(next)) return false;
    locale.value = next;
    storage?.setItem?.("novel-language", locale.value);
    if (documentRef) documentRef.cookie = `${LanguageCookieName}=${encodeURIComponent(locale.value)}; Max-Age=31536000; Path=/; SameSite=Lax${secure ? "; Secure" : ""}`;
    applyDocumentLanguage();
    return true;
  }
  applyDocumentLanguage();
  return { plugin, locale, availableLocales, setLocale, t };
}

export const LanguageCookieName = "novel_lang";
